### ISSUE TITLE
Custom Message

### ISSUE THREAD

**Issue by MubinSayed** [robotsinside/laravel-deletable#5]
I need to implement my custom message while showing errors. Can you please show me how I can implement that?

**Comment by robfrancken** [comment]
Have a look at `RobotsInside\Deletable\Requests\DeletableRequest`. It contains a `rules()` method which uses `RobotsInside\Deletable\Rules\DeletableRule`. You should be able to extend that class and define your own message(s).

It might be worth adding a feature to make this easier. I can take a look at it next week.

**Comment by robfrancken** [comment]
Hi @MubinSayed 

This feature has been added. Please check out the docs here: https://github.com/robotsinside/laravel-deletable#4-customising-the-validation-messages
