### ISSUE TITLE
Ajax Support

### ISSUE THREAD

**Issue by MubinSayed** [robotsinside/laravel-deletable#6]
Is there any way I can implement it with ajax?

**Comment by robfrancken** [comment]
Hi @MubinSayed,

It already works with Ajax, all you have to do is type-hint `RobotsInside\Deletable\Requests\DeletableRequest` in your controller method.

```php
    public function destroy(DeletableRequest $request, Post $post)
    {
        $post->delete();

        return response()->json();
    }
```

**Comment by robfrancken** [comment]
Hi @MubinSayed

Did you get it working with ajax?
